### ISSUE TITLE
AttributeError: module 'zarr' has no attribute 'MemoryStore'

### ISSUE THREAD

**Issue by geojobueno** [fastscape-lem/fastscape#37]
I'm trying to learn how to use the fastscape and using the fastscape-demo I got the error: **"AttributeError: module 'zarr' has no attribute 'MemoryStore"** when running the model (marine and margin models). 
This bug occurs using Python related to the python version 3.13.7. The same bug is happening on Binder version (https://hub.gesis.mybinder.org/user/fastscape-lem-fastscape-demo-kljn1is6/lab/tree/examples/marine_model.ipynb)
When I installed through conda using python 3.10 I got no error.

**Comment by benbovy** [comment]
Thanks for the report @geojobueno. This is because [Xarray-simlab](https://github.com/xarray-contrib/xarray-simlab) used here doesn't support Zarr 3.x yet. I works with your python 3.10 conda environment likely because Zarr 2.x is installed in that environment, which is unfortunately the best workaround right now.
